### ISSUE TITLE
Use a custom user model by default

### ISSUE THREAD

**Issue by wsot** [ackama/django-template#24]
## 🎯Aim
Apply the good practice of using a custom user model from the beginning.

## 📕Context
Good Django practice is to use a custom user model from the very beginning of a project. The template currently doesn't do that, which means any user of the template has to do so.

## 📝Relevant resources/doc's/people
Random links:
- [Learn Django: Django Custom User Model](https://learndjango.com/tutorials/django-custom-user-model)
- [The power of customizing the Django user, why you should start early](https://medium.com/@akshatgadodia/the-power-of-customising-django-user-why-you-should-start-early-e9036eae8c6d)

## ✅Acceptance Criteria

- A custom user model exists (in an `accounts` app maybe?) and is set up by default.
- Documentation and tests for the custom user model exist

**Comment by a-musing-moose** [comment]
Completed in https://github.com/ackama/django-template/pull/47 and https://github.com/ackama/django-template/pull/48
