### ISSUE TITLE
Fix vulnerabilities from gunicorn and sqlparse

### ISSUE THREAD

**Issue by zahraaalizadeh** [ackama/django-template#54]
## 🤔 Issue: 

I scanned the project using [osv-scanner](https://github.com/google/osv-scanner) and the following dependencies popped up.
| OSV URL | CVSS | Ecosystem | Package | Version | Source |
| --- | --- | --- | --- | --- | --- |
| https://osv.dev/GHSA-w3h3-4rj7-4ph4 | 8.2 | PyPI | gunicorn | 21.2.0 | template/poetry.lock |
| https://osv.dev/GHSA-2m57-hf25-phgg | 7.5 | PyPI | sqlparse | 0.4.4 | template/poetry.lock |

## 📝Steps to reproduce:

1. install [osv-scanner](https://google.github.io/osv-scanner/installation/)
2. run `osv-scanner --lockfile ./template/poetry.lock` on the root of this project

## ✅ Expected Result:

The existing vulnerabilities should be fixed:
- **gunicorn**:  updating to version 22.0.0 (more details [here](https://osv.dev/vulnerability/GHSA-w3h3-4rj7-4ph4))
- **sqlparse**: updating to version 0.5.0 (more** details [here](https://osv.dev/vulnerability/GHSA-2m57-hf25-phgg))

**Comment by G-Rath** [comment]
The first was taken care of via https://github.com/ackama/django-template/pull/53 and the second is addressed via https://github.com/ackama/django-template/pull/52

**Comment by zahraaalizadeh** [comment]
Whoops! Sorry! I should have checked the PRs!
